add_test([=[DBCoreTest.ConnectSuccess]=]  [==[/home/polinwq_534/macOS отчеты/tpmp-lab4/t/tests/runTests]==] [==[--gtest_filter=DBCoreTest.ConnectSuccess]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DBCoreTest.ConnectSuccess]=]  PROPERTIES WORKING_DIRECTORY [==[/home/polinwq_534/macOS отчеты/tpmp-lab4/t/tests]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DBCoreTest.InitFromFileFail]=]  [==[/home/polinwq_534/macOS отчеты/tpmp-lab4/t/tests/runTests]==] [==[--gtest_filter=DBCoreTest.InitFromFileFail]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DBCoreTest.InitFromFileFail]=]  PROPERTIES WORKING_DIRECTORY [==[/home/polinwq_534/macOS отчеты/tpmp-lab4/t/tests]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[DBCoreTest.CloseDB]=]  [==[/home/polinwq_534/macOS отчеты/tpmp-lab4/t/tests/runTests]==] [==[--gtest_filter=DBCoreTest.CloseDB]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[DBCoreTest.CloseDB]=]  PROPERTIES WORKING_DIRECTORY [==[/home/polinwq_534/macOS отчеты/tpmp-lab4/t/tests]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CrudTest.AddDriver]=]  [==[/home/polinwq_534/macOS отчеты/tpmp-lab4/t/tests/runTests]==] [==[--gtest_filter=CrudTest.AddDriver]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CrudTest.AddDriver]=]  PROPERTIES WORKING_DIRECTORY [==[/home/polinwq_534/macOS отчеты/tpmp-lab4/t/tests]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CrudTest.AddCar]=]  [==[/home/polinwq_534/macOS отчеты/tpmp-lab4/t/tests/runTests]==] [==[--gtest_filter=CrudTest.AddCar]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CrudTest.AddCar]=]  PROPERTIES WORKING_DIRECTORY [==[/home/polinwq_534/macOS отчеты/tpmp-lab4/t/tests]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CrudTest.AddOrder]=]  [==[/home/polinwq_534/macOS отчеты/tpmp-lab4/t/tests/runTests]==] [==[--gtest_filter=CrudTest.AddOrder]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CrudTest.AddOrder]=]  PROPERTIES WORKING_DIRECTORY [==[/home/polinwq_534/macOS отчеты/tpmp-lab4/t/tests]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CrudTest.UpdateDriver]=]  [==[/home/polinwq_534/macOS отчеты/tpmp-lab4/t/tests/runTests]==] [==[--gtest_filter=CrudTest.UpdateDriver]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CrudTest.UpdateDriver]=]  PROPERTIES WORKING_DIRECTORY [==[/home/polinwq_534/macOS отчеты/tpmp-lab4/t/tests]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CrudTest.UpdateCar]=]  [==[/home/polinwq_534/macOS отчеты/tpmp-lab4/t/tests/runTests]==] [==[--gtest_filter=CrudTest.UpdateCar]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CrudTest.UpdateCar]=]  PROPERTIES WORKING_DIRECTORY [==[/home/polinwq_534/macOS отчеты/tpmp-lab4/t/tests]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CrudTest.UpdateOrder]=]  [==[/home/polinwq_534/macOS отчеты/tpmp-lab4/t/tests/runTests]==] [==[--gtest_filter=CrudTest.UpdateOrder]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CrudTest.UpdateOrder]=]  PROPERTIES WORKING_DIRECTORY [==[/home/polinwq_534/macOS отчеты/tpmp-lab4/t/tests]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CrudTest.UpdateMileage]=]  [==[/home/polinwq_534/macOS отчеты/tpmp-lab4/t/tests/runTests]==] [==[--gtest_filter=CrudTest.UpdateMileage]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CrudTest.UpdateMileage]=]  PROPERTIES WORKING_DIRECTORY [==[/home/polinwq_534/macOS отчеты/tpmp-lab4/t/tests]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CrudTest.DeleteDriver]=]  [==[/home/polinwq_534/macOS отчеты/tpmp-lab4/t/tests/runTests]==] [==[--gtest_filter=CrudTest.DeleteDriver]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CrudTest.DeleteDriver]=]  PROPERTIES WORKING_DIRECTORY [==[/home/polinwq_534/macOS отчеты/tpmp-lab4/t/tests]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CrudTest.DeleteCar]=]  [==[/home/polinwq_534/macOS отчеты/tpmp-lab4/t/tests/runTests]==] [==[--gtest_filter=CrudTest.DeleteCar]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CrudTest.DeleteCar]=]  PROPERTIES WORKING_DIRECTORY [==[/home/polinwq_534/macOS отчеты/tpmp-lab4/t/tests]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[CrudTest.DeleteOrder]=]  [==[/home/polinwq_534/macOS отчеты/tpmp-lab4/t/tests/runTests]==] [==[--gtest_filter=CrudTest.DeleteOrder]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[CrudTest.DeleteOrder]=]  PROPERTIES WORKING_DIRECTORY [==[/home/polinwq_534/macOS отчеты/tpmp-lab4/t/tests]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[BusinessTest.CargoLimitOK]=]  [==[/home/polinwq_534/macOS отчеты/tpmp-lab4/t/tests/runTests]==] [==[--gtest_filter=BusinessTest.CargoLimitOK]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BusinessTest.CargoLimitOK]=]  PROPERTIES WORKING_DIRECTORY [==[/home/polinwq_534/macOS отчеты/tpmp-lab4/t/tests]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[BusinessTest.CargoLimitExceeded]=]  [==[/home/polinwq_534/macOS отчеты/tpmp-lab4/t/tests/runTests]==] [==[--gtest_filter=BusinessTest.CargoLimitExceeded]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BusinessTest.CargoLimitExceeded]=]  PROPERTIES WORKING_DIRECTORY [==[/home/polinwq_534/macOS отчеты/tpmp-lab4/t/tests]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[BusinessTest.ProcessOrderFail]=]  [==[/home/polinwq_534/macOS отчеты/tpmp-lab4/t/tests/runTests]==] [==[--gtest_filter=BusinessTest.ProcessOrderFail]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[BusinessTest.ProcessOrderFail]=]  PROPERTIES WORKING_DIRECTORY [==[/home/polinwq_534/macOS отчеты/tpmp-lab4/t/tests]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ReportsTest.DriverOrdersInvalidID]=]  [==[/home/polinwq_534/macOS отчеты/tpmp-lab4/t/tests/runTests]==] [==[--gtest_filter=ReportsTest.DriverOrdersInvalidID]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ReportsTest.DriverOrdersInvalidID]=]  PROPERTIES WORKING_DIRECTORY [==[/home/polinwq_534/macOS отчеты/tpmp-lab4/t/tests]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ReportsTest.MaxMileageCar]=]  [==[/home/polinwq_534/macOS отчеты/tpmp-lab4/t/tests/runTests]==] [==[--gtest_filter=ReportsTest.MaxMileageCar]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ReportsTest.MaxMileageCar]=]  PROPERTIES WORKING_DIRECTORY [==[/home/polinwq_534/macOS отчеты/tpmp-lab4/t/tests]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[ReportsTest.AllDriversStats]=]  [==[/home/polinwq_534/macOS отчеты/tpmp-lab4/t/tests/runTests]==] [==[--gtest_filter=ReportsTest.AllDriversStats]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[ReportsTest.AllDriversStats]=]  PROPERTIES WORKING_DIRECTORY [==[/home/polinwq_534/macOS отчеты/tpmp-lab4/t/tests]==] SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  runTests_TESTS DBCoreTest.ConnectSuccess DBCoreTest.InitFromFileFail DBCoreTest.CloseDB CrudTest.AddDriver CrudTest.AddCar CrudTest.AddOrder CrudTest.UpdateDriver CrudTest.UpdateCar CrudTest.UpdateOrder CrudTest.UpdateMileage CrudTest.DeleteDriver CrudTest.DeleteCar CrudTest.DeleteOrder BusinessTest.CargoLimitOK BusinessTest.CargoLimitExceeded BusinessTest.ProcessOrderFail ReportsTest.DriverOrdersInvalidID ReportsTest.MaxMileageCar ReportsTest.AllDriversStats)
